title = "Coronavirus 2020 Catastrophe"
baseURL = "https://www.20-coronavirus-20.com"
languageCode = "en-us"
theme = "ananke"

MetaDataFormat = "yaml"
DefaultContentLanguage = "en"
SectionPagesMenu = "main"
Paginate = 24
googleAnalytics = ""
enableRobotsTXT = true

[languages]
  [languages.en]
    title = "Coronavirus 2020"
    weight = 1
    [languages.en.params]
      # linkedin = "https://linkedin.com/whoever"
  [languages.da]
    title = "Coronavirus 2020"
    weight = 2
    [languages.da.params]
      # linkedin = "https://linkedin.com/fr/whoever"
      [languages.da.params.navigation]
        help = "Aide"


[sitemap]
  changefreq = "monthly"
  priority = 0.5
  filename = "sitemap.xml"

[params]
  favicon = ""
  description = "And how much of it could have been avoided"
  facebook = ""
  twitter = ""
  instagram = ""
  youtube = ""
  github = ""
  gitlab = ""
  linkedin = ""
  mastodon = ""
  slack = ""
  stackoverflow = ""
  # choose a background color from any on this page: http://tachyons.io/docs/themes/skins/ and preface it with "bg-"
  background_color_class = "bg-black"
  featured_image = "/images/gohugo-default-sample-hero-image.jpg"
  recent_posts_number = 2
