title = "20-CORONAVIRUS-20"
baseURL = "https://www.20-coronavirus-20.com"
languageCode = "en-us"
theme = "ananke"

MetaDataFormat = "yaml"
DefaultContentLanguage = "en"
SectionPagesMenu = "main"
Paginate = 48
googleAnalytics = "UA-89827484-2"
enableRobotsTXT = true

disqusShortname = "20-coronavirus-20"

[languages]
  [languages.en]
    title = "20-CORONAVIRUS-20"
    languageName = "English 🇺🇸"
    weight = 1
    [languages.en.params]
      languageName = "English 🇺🇸"
      # linkedin = "https://linkedin.com/whoever"
  [languages.da]
    title = "20-CORONAVIRUS-20"
    languageName = "Dansk 🇩🇰"
    weight = 2
    [languages.da.params]
      languageName = "Dansk 🇩🇰"
      # linkedin = "https://linkedin.com/fr/whoever"
      [languages.da.params.navigation]
        help = "Aide"


[sitemap]
  changefreq = "monthly"
  priority = 0.5
  filename = "sitemap.xml"

  [taxonomies]
    brands = "brands"
    cases = "cases"
    cm = "cm"
    emner = "emner"
    kunder = "kunder"
    tools = "tools"
    genrer = "genrer"
    skribenter = "skribenter"

  [privacy]
    [privacy.disqus]
      disable = true
    [privacy.googleAnalytics]
      anonymizeIP = false
      disable = false
      respectDoNotTrack = true
      useSessionStorage = false
    [privacy.instagram]
      disable = false
      simple = false
    [privacy.twitter]
      disable = false
      enableDNT = false
      simple = false
    [privacy.vimeo]
      disable = false
      simple = false
    [privacy.youtube]
      disable = false
      privacyEnhanced = true

      [related]

      threshold = 80
      includeNewer = true
      toLower = false

      [[related.indices]]
      name = "keywords"
      weight = 100
      [[related.indices]]
      name  = "date"
      weight = 10
      pattern = "2006"


[params]
  mainSections = ["blog", "book"]
  favicon = ""
  description = "And how much of it could have been avoided"
  facebook = "https://www.facebook.com/lennartkiil/"
  twitter = "https://twitter.com/lennartkiil/"
  instagram = ""
  youtube = ""
  github = ""
  gitlab = ""
  linkedin = "https://www.linkedin.com/in/lennartkiil/"
  mastodon = ""
  slack = ""
  stackoverflow = ""
  # choose a background color from any on this page: http://tachyons.io/docs/themes/skins/ and preface it with "bg-"
  background_color_class = "bg-near-black"
  cover_dimming_class = "bg-near-black-60"
  featured_image = "/images/coronavirus.jpg"
  recent_posts_number = 2
  custom_css = ["css/custom.css"]
