title = "Coronavirus"
baseURL = "https://www.20-coronavirus-20.com"
languageCode = "en-us"
theme = "ananke"

MetaDataFormat = "yaml"
DefaultContentLanguage = "en"
SectionPagesMenu = "main"
Paginate = 48
googleAnalytics = "UA-89827484-2"
enableRobotsTXT = true

[languages]
  [languages.en]
    title = "Coronavirus"
    languageName = "English 🇺🇸"
    weight = 1
    [languages.en.params]
      languageName = "English 🇺🇸"
      # linkedin = "https://linkedin.com/whoever"
  [languages.da]
    title = "Coronavirus"
    languageName = "Dansk 🇩🇰"
    weight = 2
    [languages.da.params]
      languageName = "Dansk 🇩🇰"
      # linkedin = "https://linkedin.com/fr/whoever"
      [languages.da.params.navigation]
        help = "Aide"


[sitemap]
  changefreq = "monthly"
  priority = 0.5
  filename = "sitemap.xml"

  [privacy]
    [privacy.disqus]
      disable = false
    [privacy.googleAnalytics]
      anonymizeIP = false
      disable = false
      respectDoNotTrack = true
      useSessionStorage = false
    [privacy.instagram]
      disable = false
      simple = false
    [privacy.twitter]
      disable = false
      enableDNT = false
      simple = false
    [privacy.vimeo]
      disable = false
      simple = false
    [privacy.youtube]
      disable = false
      privacyEnhanced = true


[params]
  mainSections = ["blog", "book"]
  favicon = ""
  description = "And how much of it could have been avoided"
  facebook = ""
  twitter = ""
  instagram = ""
  youtube = ""
  github = ""
  gitlab = ""
  linkedin = ""
  mastodon = ""
  slack = ""
  stackoverflow = ""
  # choose a background color from any on this page: http://tachyons.io/docs/themes/skins/ and preface it with "bg-"
  background_color_class = "bg-near-black"
  cover_dimming_class = "bg-near-black-60"
  featured_image = "/images/coronavirus.jpg"
  recent_posts_number = 2
  custom_css = ["css/custom.css"]
